### ISSUE TITLE
能不能考虑把 rapid 主题单独开个仓库

### ISSUE THREAD

**Issue by XhstormR** [coderzh/coderzh-hugo-blog#1]
我发现博主你的主题不错，用了下，有些你的图片，还有 Google Analytics，如果能够单独开个仓库，添加些配置：首页图片、是否开启Google Analytics 就好了。

BTW，我是看你翻译的中文文档，瞬间决定从 hexo 转到 hugo，一个 exe 文件就解决问题真是太爽了。

**Comment by coderzh** [comment]
Fixed: https://github.com/coderzh/hugo-rapid-theme
